cookproject/CookSpot/urls.py
from django.urls import path
from . import views
from .views import delete_view

app_name = 'web'
urlpatterns = [
path("users/", views.users, name="users"),
    path("allrecipes/", views.allrecipes, name="allrecipes"),
    path("", views.homepage, name="home"),
    path("homepage/", views.homepage, name="home"),
    path("accounts/login/", views.login, name='login'),
    path("accounts/logout/", views.homepage, name="home"),
    path("signup/", views.signup, name='signup'),
    path("<str:User_username>/newrecipe/", views.newrecipe, name='newrecipe'),
    path('<str:User_username>/recipe/<str:Recipe_name>/',
         views.recipe, name='recipe'),
    path("newrecipe/post/", views.newrecipe_post, name='newrecipe_post'),
    path("signup/post/", views.signup_post, name='signup_post'),
    path("<str:User_username>/myprofile/", views.profile, name="myprofile"),
    path("meets/", views.meets, name="meets"),
    path('<str:User_username>/meet/<str:Meets_name>/', views.meet, name='meet'),
    path('<str:User_username>/meet/<str:Meets_name>/join',
         views.meetjoin, name='meetjoin'),
    path('<str:User_username>/meet/<str:Meets_name>/invite',
         views.meetinvite, name='meetinvite'),
    path('<str:User_username>/meet/<str:Meets_name>/useringredients', views.standalonemeet, name='standalonemeet'),
    path('<str:User_username>/meet/<str:Meets_name>/rate/<str:Target_username>',
         views.meetrate, name='rate'),
    path('rate/post', views.meetrate_post, name='rate_post'),
    path('editrate/post', views.editrate_post, name='editrate_post'),
    path('<str:User_username>/newmeet/', views.newmeet, name='newmeet'),
    path('<str:User_username>/mycookgraphy/',
         views.myrecipes, name='mycookgraphy'),
    path('newmeet/post', views.newmeet_post, name='newmeet_post'),
    path('search/', views.search, name="search-things"),
    path('searchmeets/', views.searchmeets, name="search-meets"),
    path('editUserDetails', views.editUserDetails, name="editUserDetails"),
    path("<int:id>/addtofav/<str:ur>", views.add_to_fav, name="addtofav"),
    path('<id>/delete', delete_view, name='delete_fav'),
    path("recipe_delete/<int:rec_id>", views.recipe_delete, name='recipe_delete'),
    path("editRecipe/<str:User_username>/<str:Recipe_name>", views.edit_recipe, name='edit_recipe'),
    path("editRecipe/<str:User_username>/<str:Recipe_name>/post",views.edit_recipe_post, name='edit_recipe_post'),
    path("meet_delete/<int:meet_id>", views.meet_delete, name='meet_delete'),
    path("editMeet/<str:Meet_name>", views.edit_meet, name='edit_meet'),
    path("editMeet/<str:Meet_name>/post",views.edit_meet_post, name='edit_meet_post'),
    path("<str:Meets_name>/uninvite/<str:User_username>", views.uninvite, name='uninvite'),
]

cookproject/cookproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("CookSpot.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cookproject/CookSpot/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db.models.constraints import UniqueConstraint
from django.db.models.fields.related import ManyToManyField
from django.dispatch import receiver
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models.signals import post_save

# Create your models here.

User = settings.AUTH_USER_MODEL


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    profile_photo = models.URLField()

    def get_av_rating(self):
        averagescore = 0
        for rating in (self.user.gottenratings.all()):
            averagescore += rating.rating
        try:
            averagescore /= len(self.user.gottenratings.all())
            averagescore = round(averagescore, 2)
        except(ZeroDivisionError):
            averagescore = "No Ratings"
        return averagescore

    def __str__(self):
        return self.user.username


# create profile when registering new user
@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=254)
    description = models.TextField()
    image = models.URLField()
    # image = models.ImageField(null=True, blank=True, upload_to="images/", height_field=None, width_field=None, max_length=100)
    # properties = models.CharField(max_length=254)
    tags = models.CharField(max_length=254)
    difficulty = models.CharField(max_length=254)
    preparationtime = models.CharField(max_length=254)
    cookingtime = models.CharField(max_length=254)
    instructions = models.TextField()

    def __str__(self):
        return self.name


class Ingredients(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.PROTECT, related_name='chosenuser')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=254)
    amount = models.CharField(max_length=254)
    measurement = models.CharField(max_length=254)
    def __str__(self):
        return self.name

class Meets(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    maximumparticipants = models.IntegerField(blank=True, null=True)
    participants = ManyToManyField(
        User, related_name="participants", blank=True)
    name = models.CharField(max_length=254)
    date = models.DateField()
    desc = models.TextField()
    location = models.CharField(max_length=254)

    def participating(self):
        return len(self.participants.all())

    def __str__(self):
        return self.name


class UserRating(models.Model):
    fromuser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='givenratings')
    touser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='gottenratings')
    meet = models.ForeignKey(
        Meets, blank=True, null=True, on_delete=models.SET_NULL)
    rating = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)])

    def __str__(self):
        return str(self.rating) + " by " + str(self.fromuser) + " for " + str(self.touser) + " from " + str(self.meet)

    class META:
        constraints = [
            models.UniqueConstraint(
                fields=["fromuser", "touser", "meet"], name="1 Rating per Meet")
        ]


class Invite(models.Model):
    fromuser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='giveninvites')
    touser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='gotteninvites')
    meet = models.ForeignKey(Meets, on_delete=models.CASCADE)

    def __str__(self):
        return "Invite by " + str(self.fromuser) + " to " + str(self.touser) + " for " + str(self.meet) + " on " + str(
            self.meet.date)


class Favourite(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name='favourites')
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='favrecipe', blank=True, null=True)
    cookfav = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='favcook', null=True, blank=True)

cookproject/templates/editMeet.html
{% extends "index.html" %}
{% block css %}
  <style>
    label {
      color: white;
      font-size: 20px;
    }
    h2, label{font-family: 'Barlow Condensed', sans-serif;}
  </style>
{% endblock css %}
{% block title %} Edit meet {% endblock%}
{% block content %}
<h1>Edit your Meet!</h1>
<form action="{% url 'web:edit_meet_post' meet.name%}" method="POST" enctype="multipart/form-data">{% csrf_token %}
  <input name="username" value="{{user.username}}" hidden/>
  <div class="form-row">
    <div class="form-group col-md-6" >
      <label for="meetName">Name</label>
      <input required type="text" value={{meet.name}} class="form-control" id="meetName" placeholder="Enter a fun name for your m-eat!" name="meetName">
    </div>
    <div class="form-group col-md-6">
      <label for="recipe">What are you cooking?</label>
      <select id="recipe" class="form-control" name="recipe">
        <option value="none" selected>Choose a recipe</option>
        {% for recipe in user.recipe_set.all %}
            <option value="{{recipe.name}}" >{{recipe.name}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="meetDate">When?</label>
    <input type="date" class="form-control" id="meetDate" name="meetDate" value={{meet.date}}>
  </div>
  <div class="form-group">
    <label for="meetDate">How many People?</label>
    <input type="text" class="form-control" id="pnumber" name="pnumber" value={{meet.maximumparticipants}}
      placeholder="Enter a number of people" required>
  </div>
  <div class="form-group">
    <label for="inputAddress2">Description (Optional) </label>
    <input type="text" class="form-control" id="inputAddress2" name="description" value={{meet.desc}}>
  </div>
   
  <button type="submit" class="btn btn-primary">Add</button>
</form>
{% endblock %}

cookproject/templates/editRecipe.html
{% extends "index.html" %}
{% block css %}
  <style>
    label {
      color: white;
      font-size: 20px;
    }
    h2, label{font-family: 'Barlow Condensed', sans-serif;}
    th {
      color: white;
      font-size: 20px;
      
    }
  </style>
{% endblock css %}
{% block title %} Edit recipe {% endblock%}
{% block content %}
<h3>Edit your recipe</h3>
<form action="{% url 'web:edit_recipe_post' user.username recipe.name %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <input name="username" value="{{user.username}}" hidden/>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="recipeName">Name</label>
        <input required type="text" value="{{recipe.name}}" class="form-control" id="recipeName" placeholder="Name" name="recipename">
      </div>
      <div class="form-group col-md-6">
        <label for="recipeLevel">Level</label>
        <select id="recipeLevel" value="{{recipe.difficulty}}" class="form-control" name="difficulty">
          <option value="{{recipe.difficulty}}"  selected>{{recipe.difficulty}}</option>
          <option value="None" >Anyone can do it</option>
          <option value="Easy" >Beginner</option>
          <option value="Intermediate" >Intermediate</option>
          <option value="Difficult" >Difficult</option>
          <option value="Professional" >Professional</option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <label for="recipeTags">Tags</label>
      <input type="text" class="form-control" id="recipeTags" name="tags" value="{{recipe.tags}}"
        placeholder="Enter your tags separated by commas. Example: 'chocolate, birthday cake, frosting' ">
    </div>
    <div class="form-group">
      <label for="inputAddress2">Description (Optional) </label>
      <input type="text" class="form-control" id="inputAddress2" name="description" value="{{recipe.description}}"
        placeholder="Write something about the dish, history etc.">
    </div>
    <div class="form-group">
      <label for="inputAddress3">Preparation Time</label>
      <input type="text" value="{{recipe.preparationtime}}" class="form-control" id="inputAddress3" name="preparationtime"
        placeholder="Preparation Time">
    </div>
    <div class="form-group">
      <label for="inputAddress4">Cooking Time</label>
      <input type="text" value="{{recipe.cookingtime}}" class="form-control" id="inputAddress4" name="cookingtime"
        placeholder="Time Required to Cook">
    </div>
    <div class="form-group">
      <label for="inputAddress5">Image</label>
      <input type="url" alt="here goes picture" placeholder="Enter the URL of the image" class="form-control" id="inputAddress5" name="image" pattern="https://.*">
    </div>
  
    
    <div class="input-group mb-3">
      <label for="ingredientsNumber">do you want to add more ingredients?</label>
      <input type="number" class="form-control" id="ingredientsNumber" value="{{recipe.ingredients_set.all|length }}">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button" onclick="ingredients()">Add the ingredients</button>
      </div>
    </div>
    
    <div class="form-inline">
      <div class="form-group col-md-6">
        <div id="ingredientsTable">
            <table>
                <thead>
                  <tr>
                    <th scope="col">Amount</th>
                    <th scope="col">Unit</th>
                    <th scope="col">Ingredient</th>
                  </tr>
                </thead>
                <tbody id="ingredientsBody">
                    {% for Ingredients in recipe.ingredients_set.all %}
                    <tr>
                        <td><label for="ingredientAmount"></label>
                        <input type="text" value="{{Ingredients.amount}}" class="form-control" id="ingredientAmount" name="ingredientamount[]"  placeholder="Amount for 4 People">
                      </td>
                      <td>
                        <label for="ingredientMeasurement"></label>
                        <select id="ingredientMeasurement" class="form-control" name="ingredientmeasurement[]" value="{{Ingredients.measurement}}">
                          <option value="{{Ingredients.measurement}}" selected>{{Ingredients.measurement}}</option>
                          <option value="g">g</option>
                          <option value="lb">lb</option>
                          <option value="oz">oz</option>
                          <option value="p">p</option>
                          <option value="c">c</option>
                          <option value="ml">ml</option>
                          <option value="tsp">tsp</option>
                          <option value="Tbsp">Tbsp</option>
                        </select>
                      </td>
                      <td><label for="ingredientName"></label>
                        <input type="text" class="form-control" id="ingredientName" placeholder="Leave Empty to Delete" name="ingredientname[]" value="{{Ingredients.name}}">
                      </td>
                    </tr>
                    
                    {% endfor %}
                </tbody>
              </table>
        </div>
        
  
      </div>
    </div>
    <div class="form-group">
      <label for="recipeDirections">Directions</label>
      <textarea class="form-control" value="{{recipe.instructions}}" name="instructions" id="recipeDirections" rows="3">{{recipe.instructions}}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
  </form>
  <script>
    function ingredients() {
      var val = document.getElementById("ingredientsNumber").value;
      if(val) {
        for(i=0;i<parseInt(val);i++){
        document.getElementById("ingredientsBody").innerHTML += 
        `<td><label for="ingredientAmount"></label>
          <input type="text" class="form-control" id="ingredientAmount" name="ingredientamount[]"  placeholder="Amount for 4 People">
        </td>
        <td>
          <label for="ingredientMeasurement"></label>
          <select id="ingredientMeasurement" class="form-control" name="ingredientmeasurement[]">
            <option selected>Choose...</option>
            <option value="g">g</option>
            <option value="lb">lb</option>
            <option value="oz">oz</option>
            <option value="p">p</option>
            <option value="c">c</option>
            <option value="ml">ml</option>
            <option value="tsp">tsp</option>
            <option value="Tbsp">Tbsp</option>
          </select>
        </td>
        <td><label for="ingredientName"></label>
          <input type="text" class="form-control" id="ingredientName"  name="ingredientname[]">
        </td>`
      }
              
      }
  } 
  </script>
{% endblock %}

cookproject/templates/recipe.html
{% extends "index.html" %}
{% block css %}
  <style>
    .card-body  {
        font-size: 1.2em;
        font-family: 'Quicksand', sans-serif;
    }
    
  </style>
{% endblock css %}
{% block title %} {{recipe.name}} {% endblock%}
{% block content %}
<div class="row">
    <!-- Image & description -->
    <div class="col cols-12 offset-md-1">
        <div class="row">
                <h2>{{recipe.name}} - <a href="{% url 'web:myprofile' recipe.user %}">{{user.username}}</a></h2>
                {% if recipe.user == request.user %}
                    <button type="button" class="fa fa-trash" style="font-size:24px; position: relative; margin:10px;
                     background-color: none;" data-toggle="modal" data-target="#deleteModal"></button>
                    <!-- Modal -->
                    <div class="modal"  id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="deleteModal"> Are you sure that you want to delete your recipe {{recipe.name}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                                Deleting this recipe will also delete it from any meets and favorite recipes of other users.
                            </div>
                            <div class="modal-footer">
                            <a href="{% url 'web:recipe_delete' recipe.id  %}"  class="btn">Yes, delete</a>
                            <a href="{% url 'web:recipe' recipe.user recipe.name  %}" type="button" class="btn">No, go back</a>
                            </div>
                        </div>
                        </div>
                    </div>
                    <a href="{% url 'web:edit_recipe' user.username recipe.name %}" type="button">
                        <i class="fa fa-pencil" style="font-size:24px; position: relative; margin:10px; background-color:white"></i>
                    </a>
                {% endif %}

        </div>
        <h4 style="color: white;">{{recipe.description}}</h4>
        <div style="padding: 10px;">
            <figure >
             <img
              {% if recipe.image %}
                src="{{recipe.image}}"
              {% else %}
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/488px-No-Image-Placeholder.svg.png"
              {% endif %} 
              class="img-fluid"  alt="Responsive Image" 
              width="307" height="240" /> 
          </figure>
          </div>
    </div>
    <!-- Details -->
    <div class="col-md-6 cols-12 align-self-center offset-md-1">
        <h4 style="color: white;">Details</h4>
        <div class="card" style="background-color: #9DC88D; width: max-content;">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    Tags: {{recipe.tags}} <br>
                    Difficulty: {{recipe.difficulty}}<br>
                    Preparation Time: {{recipe.preparationtime}}<br>
                    Cooking time: {{recipe.cookingtime}}<br>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- instructions and ingredients-->
<div class="row">

    <div class="col-md-4 cols-12 offset-md-1">
        <h4>Ingredients</h4>
        <a href="{% url 'web:addtofav' id=recipe.id  ur='rec' %}">Add to Fav</a>
        <table class="table">
            <tbody style="color: white; font-size: 1.1em;"> 
              {% for Ingredients in recipe.ingredients_set.all %}
              <tr>
                  <td>{{Ingredients.name}}</td>
                  <td>{{Ingredients.amount}}{{Ingredients.measurement}}
                  </td>
              <td><input type="checkbox" name="checkbox" id="checkbox_id" value="value">
                  <label for="checkbox_id"></label>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-4 cols-12 offset-md-1">
        <h4 style="color: white;">Instructions</h4>
        <div class="card" style="background-color: #9DC88D; width: auto;">
            <div class="card-body">
                <h4 class="card-title"></h4>
                <p> {{recipe.instructions}}</p>
            </div>
        </div>
       
        
    </div>

</div>

{% endblock %}

cookproject/templates/user.html
{% extends "index.html" %}
{% block css %}
<style>
  @import url('https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap');  
  h1 {
    font-family: 'Open Sans Condensed', sans-serif;
    font-size: 60px;
  }
  img {
    border-radius: 70%;
    width: 150px;
  }
  @media (max-width: 767px) {
    img { 
      display: inline-block;
    }
  }
  @media (min-width: 768px){
    img {
    float: right;
    }
  }
  .card{
    background-color: #9DC88D !important;
    margin: 10px;
  }
  .card  button, .btn{
    background-color: white !important;
    color: black !important;
  }
  
  .card li > a {
    background-color: #9DC88D !important;
    
  }

  .card li {
    background-color: #9DC88D;
  }
  h4 {color: black;}

  #detailsList > li {
    background-color: #9DC88D;
    color: white;
    font-size: 19px;
  }
</style>
{% endblock %}

{% block title %}{{user.username}} | Cookspot profile{% endblock %}
{% block content %}
<div class="row p-2">
  <div class="col-sm-5 col-md-5 ">
    {% if user.profile.profile_photo %}
    <img src="{{user.profile.profile_photo}}">
    {% else %}
    here goes image
    {% endif %}
  </div>
  <div class="col-sm-7 col-md-7 align-self-center">
    <h3>|{{user.first_name}} {{user.last_name}}</h3>
    {% if request.user.pk != user.pk %}
    <a href="{% url 'web:addtofav' id=user.id ur='cook'  %}">Add to Fav</a>
    {% endif %}
  </div>
</div>

{% if request.user.pk == user.pk %}
<div class="row py-2">
  <div class="col-sm-12 col-md-4 ">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Details</h5>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Edit profile
          details</button>
        <ul class="list-group list-group-flush" id="detailsList">
          <li class="list-group-item">My username: {{user.username}}</li>
          <li class="list-group-item">My email: {{user.email}}</li>
          <li class="list-group-item">About me: {{user.profile.bio}}</li>
          <li class="list-group-item">Average Rating: {{user.profile.get_av_rating}}</li>
        </ul>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form method="POST" action="{% url 'web:editUserDetails' %}"> {% csrf_token %}
                  <div class="form-row">
                    <div class="col">
                      <input type="text" name="firstName" class="form-control" placeholder="First name">
                    </div>
                    <div class="col">
                      <input type="text" name="lastName" class="form-control" placeholder="Last name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="username" class="col-form-label">Username:</label>
                    <input type="text" name="username" class="form-control" id="username">
                  </div>
                  <div class="form-group">
                    <label for="email" class="col-form-label">Email:</label>
                    <input type="email" name="email" class="form-control" id="email"></textarea>
                  </div>
                  <div class="form-group">
                    <label for="bio" class="col-form-label">Bio</label>
                    <input type="text" name="bio" class="form-control" id="bio"></textarea>
                  </div>
                  <div class="form-group">
                    <label for="image">Add a profile picture!</label>
                    <input type="url" alt="here goes picture" placeholder="Enter the URL of the image"
                      class="form-control" id="image" name="image" pattern="https://.*">
                  </div>
                  <button type="submit" class="btn btn-primary">Add changes</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-12 col-md-4 ">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">My recipes</h5>
      </div>
      <ul class="list-group list-group-flush">
        {% for recipe in user.recipe_set.all %}
        <li class="list-group-item"><a href="/{{user.username}}/recipe/{{recipe.name}}">{{recipe.name}}</a></li>
        {% endfor %}
      </ul>
      <a href="/{{user.username}}/newrecipe/" class="btn btn-info" role="button">Add New Recipe</a>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">My Favourite recipe</h5>
      </div>
      {% for rec in fav_list%}
      {% if rec.recipe %}
      <li class="list-group-item">
        <a href="/{{rec.recipe.user}}/recipe/{{rec.recipe.name}}">{{rec.recipe.name}}</a>
        <a href="{% url 'web:delete_fav' id=rec.id  %}"><i class="fa fa-trash"
            style="font-size:24px; position: absolute; right: 10px"></i></a>
      </li>
      {% endif %}
      {% endfor %}

    </div>
  </div>

  <div class="col-sm-12 col-md-4 ">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Meets that you have organized</h5>
      </div>
      {% for meet in user.meets_set.all %}
      <li class="list-group-item"><a href="/{{user.username}}/meet/{{meet.name}}">{{meet.name}}</a></li>
      {% endfor %}
      <a href="/{{user.username}}/newmeet/" class="btn btn-info" role="button">Create a new meet</a>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">My Favourite Cooks</h5>
      </div>
      {% for rec in fav_list%}
      {% if rec.cookfav %}
      <li class="list-group-item"><a href="/{{rec.cookfav}}/myprofile">{{rec.cookfav.username}}</a>
        <a href="{% url 'web:delete_fav' id=rec.id  %}"><i class="fa fa-trash"
            style="font-size:24px; position: absolute; right: 10px"></i></a>
      </li>
      {% endif %}
      {% endfor %}
    </div>
  </div>


  <div class="col-sm-12 col-md-4 ">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Meets that you have participated in.</h5>
      </div>
      {% for meet in user.participants.all %}
      <li class="list-group-item"><a href="/{{meet.user}}/meet/{{meet.name}}">{{meet.name}}</a></li>
      {% endfor %}
    </div>
  </div>

  <div class="col-sm-12 col-md-4 ">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Your Invites:</h5>
      </div>
      {% for invite in user.gotteninvites.all %}
      <li class="list-group-item"><a href="/{{invite.meet.user}}/meet/{{invite.meet.name}}">{{invite}}</a></li>
      {% endfor %}
    </div>
  </div>
  {% else %}
  <div class="row py-2">
    <div class="col-sm-12 col-md-4 ">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Details</h5>
          <ul class="list-group list-group-flush" id="detailsList">
            <li class="list-group-item">Username: {{user.username}}</li>
            <li class="list-group-item">Email: {{user.email}}</li>
            <li class="list-group-item">About {{user.username}}: {{user.profile.bio}}</li>
            <li class="list-group-item">Average Rating: {{user.profile.get_av_rating}}</li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-4 ">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Recipes of {{user.username}}</h5>
        </div>
        <ul class="list-group list-group-flush">
          {% for recipe in user.recipe_set.all %}
          <li class="list-group-item"><a href="/{{user.username}}/recipe/{{recipe.name}}">{{recipe.name}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col-sm-12 col-md-4 ">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Meets of {{user.username}}</h5>
        </div>
        {% for meet in user.meets_set.all %}
        <li class="list-group-item"><a href="/{{user.username}}/meet/{{meet.name}}">{{meet.name}}</a></li>
        {% endfor %}
      </div>
    </div>
    {% endif %}


    {% endblock %}